---
functional:
  - Пользователь должен иметь возиожность фильтровать задания
  - Пользователь должен иметь возможность просматривать информацию об игроках
  - Пользователь должен иметь возможность писать сообщения в чат
  - Пользователь должен иметь возможность просматривать статистику игроков
  - Пользователь должен иметь возможность проводить игры без регистрации
  - Пользователь должен иметь возможность наблюдать за другими играми
  - Пользователь должен иметь возможность вступать в игры
  - Пользователь должен иметь возможность просматривать информацию об игроках
  - Пользователь должен иметь возможность создавать собственную игру


non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (Chrome, Opera, Yandex)
implicit:
  - Должна присутствовать авторизация и регистрация пользователя.
  - Сайт должен быть на русском и английском языке
